base:
  project: Deep_Learning

  data_source: s3://mri-dl/*

load_data:
  num_classes: 4
  raw_data: s3://mri-dl/*
  preprocessed_data: data/processed
  full_path: s3://mri-dl/*

train_split:
  split_ratio: 80

model:
  name: VGG19
  trainable: True
  train_path: data/processed/train
  test_path: data/processed/test
  image_size: [255,255]
  loss: 'categorical_crossentropy'
  optimizer: 'adam'
  metrics: ['accuracy']
  epochs: 6
  sav_dir: saved_models/trained.h5

img_augment:
  rescale: 1./255,
  shear_range: 0.2
  zoom_range: 0.20
  horizontal_flip: True
  vertical_flip: True
  batch_size: 18
  class_mode: 'categorical'
  web_model_directory: models/trained.h5

# model_dir: saved_models

# web_model_directory: models/trained.h5

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: Deep_Learning_MLOps
  run_name: mlops
  registered_model_name: Deep_Learning
  remote_server_uri: http://127.0.0.1:5000